### ISSUE TITLE
Fails to create page object

### ISSUE THREAD

**Issue by anand-chavan-qatoolist** [nvreynolds/refract#1]
irb(main):002:0> require 'refract'
=> true
irb(main):003:0> Refract.create('https://facebook.com')
Traceback (most recent call last):
       16: from /home/anchavan/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
       15: from (irb):3
       14: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/refract-0.0.0/lib/refract.rb:7:in `create'
       13: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spidr-0.6.0/lib/spidr/spidr.rb:53:in `site'
       12: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spidr-0.6.0/lib/spidr/agent.rb:274:in `site'
       11: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spidr-0.6.0/lib/spidr/agent.rb:355:in `start_at'
       10: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spidr-0.6.0/lib/spidr/agent.rb:373:in `run'
        9: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spidr-0.6.0/lib/spidr/agent.rb:665:in `visit_page'
        8: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spidr-0.6.0/lib/spidr/agent.rb:599:in `get_page'
        7: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spidr-0.6.0/lib/spidr/agent.rb:788:in `prepare_request'
        6: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spidr-0.6.0/lib/spidr/agent.rb:605:in `block in get_page'
        5: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spidr-0.6.0/lib/spidr/agent.rb:669:in `block in visit_page'
        4: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spidr-0.6.0/lib/spidr/agent.rb:669:in `each'
        3: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spidr-0.6.0/lib/spidr/agent.rb:669:in `block (2 levels) in visit_page'
        2: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spidr-0.6.0/lib/spidr/agent/events.rb:233:in `block in every_html_page'
        1: from /home/anchavan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/refract-0.0.0/lib/refract.rb:9:in `block (2 levels) in create'
NoMethodError (undefined method `downcase' for nil:NilClass)
irb(main):004:0> clear
Traceback (most recent call last):
        2: from /home/anchavan/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        1: from (irb):4
NameError (undefined local variable or method `clear' for main:Object)
Did you mean?  caller

**Comment by nvreynolds** [comment]
i didn't test this out much.  feel free to make a PR

**Comment by nvreynolds** [comment]
https://rubygems.org/gems/refract/versions/0.0.2

`gem update refract`

and try again
